### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by stylesuxx** [mathiasvr/real-things-with-funny-names#1]
> My all time favorite method for sorting bubbles.

Very inefficient, but simple sorting algorithm.

https://en.wikipedia.org/wiki/Bubble_sort

**Comment by mathiasvr** [comment]
Haha yes of course!

Good to see you found my weird repo! 😆

**Comment by mathiasvr** [comment]
Unfortunately, the Bubbles emoji is still only a candidate for inclusion... 😃
